In [1]:
import numpy as  np

In [2]:
lst = np.array([10,20,30,49])

In [3]:
lst

array([10, 20, 30, 49])

In [5]:
lst = np.array([[10,20,30],[22,33,44]])

In [6]:
print(lst)

[[10 20 30]
 [22 33 44]]


In [7]:
lst.ndim

2

In [8]:
lst.shape

(2, 3)

In [9]:
lst.size

6

In [11]:
lst.dtype

dtype('int32')

In [13]:
lst

array([[10, 20, 30],
       [22, 33, 44]])

In [14]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
lst.dtype

dtype('int32')

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,120,7)

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92,  99, 106, 113])

In [18]:
np.repeat(10,7)

array([10, 10, 10, 10, 10, 10, 10])

In [19]:
lst = np.array([10,20,40,40,'hello'])

In [20]:
lst

array(['10', '20', '40', '40', 'hello'], dtype='<U11')

In [21]:
lst.dtype

dtype('<U11')

In [22]:
np.tile(lst,2)

array(['10', '20', '40', '40', 'hello', '10', '20', '40', '40', 'hello'],
      dtype='<U11')

In [28]:
lst = np.array([[2,5,7],[3,9,12]])

In [29]:
lst

array([[ 2,  5,  7],
       [ 3,  9, 12]])

In [30]:
newList = lst.T

In [31]:
newList

array([[ 2,  3],
       [ 5,  9],
       [ 7, 12]])

In [32]:
lst

array([[ 2,  5,  7],
       [ 3,  9, 12]])

In [33]:
lst = np.arange(12)

In [34]:
lst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
lst*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [36]:
lst+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
lst1 = [10,20,3]

In [39]:
lst2 = [100,100,100]

In [40]:
lst1+lst2

[10, 20, 3, 100, 100, 100]

In [41]:
lst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
lst.max()

11

In [43]:
lst.mean()

5.5

In [44]:
lst.sum()

66

In [46]:
np.mean(lst)

5.5

In [51]:
tensor = np.arange(0,120,10).reshape(3,4)

In [52]:
tensor

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [53]:
horizon = np.array([-5,-10,-15,-20])

In [54]:
tensor*horizon

array([[    0,  -100,  -300,  -600],
       [ -200,  -500,  -900, -1400],
       [ -400,  -900, -1500, -2200]])

In [55]:
tensor+horizon

array([[-5,  0,  5, 10],
       [35, 40, 45, 50],
       [75, 80, 85, 90]])

In [57]:
tensor

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [59]:
tensor.mean(axis=0) # axios 0 means column wise, down the rows

array([40., 50., 60., 70.])

In [61]:
tensor.mean(axis=1) ## row wise

array([15., 55., 95.])

In [62]:
lst1

[10, 20, 3]

In [63]:
lst1[0]

10

In [64]:
lst1[1]

20

In [65]:
lst1

[10, 20, 3]

In [66]:
lst1 = np.arange(1,20,2)

In [67]:
lst1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [69]:
lst1[1:6] # same as python list, slicing

array([ 3,  5,  7,  9, 11])

In [70]:
tensor

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [71]:
tensor[1,2]

60

In [74]:
matrix1 = np.array([1,3,2,99,797])

In [75]:
matrix1

array([  1,   3,   2,  99, 797])

In [76]:
matrix2=matrix1

In [77]:
matrix3 = matrix1.copy()

In [81]:
matrix1[0] = 107

In [82]:
matrix1

array([107,   3,   2,  99, 797])

In [83]:
matrix2

array([107,   3,   2,  99, 797])

In [84]:
matrix3

array([  1,   3,   2,  99, 797])

In [85]:
matrix1 = [[1,23],[4,5,6],[[99,77]]]

In [86]:
matrix2 = matrix1.copy()

In [87]:
matrix1[2][0][1] = 1009

In [88]:
matrix1

[[1, 23], [4, 5, 6], [[99, 1009]]]

In [89]:
matrix2

[[1, 23], [4, 5, 6], [[99, 1009]]]