In [1]:
import numpy as np

In [4]:
array1 = np.array([1,2,3,4,5])

In [5]:
print(array1,type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
lst = [10,20,30,40,50]
array2 = np.array(lst)

In [8]:
print(array2,type(array2))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [11]:
array2d = np.array([[2,3,4],[4,5,6],[78,1,23]])

In [12]:
print(array2d,type(array2d))

[[ 2  3  4]
 [ 4  5  6]
 [78  1 23]] <class 'numpy.ndarray'>


In [13]:
array2d.shape

(3, 3)

In [14]:
array1

array([1, 2, 3, 4, 5])

In [16]:
array1[1]

2

In [17]:
array2d

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [78,  1, 23]])

In [18]:
array2d[1]

array([4, 5, 6])

In [19]:
array2d.ndim

2

In [20]:
array2d.shape

(3, 3)

In [21]:
array2d

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [78,  1, 23]])

In [22]:
array2d.size

9

In [23]:
array2d.itemsize

4

In [24]:
array2d.dtype

dtype('int32')

In [27]:
array1d = np.arange(0,4)

In [30]:
array1d

array([0, 1, 2, 3])

In [31]:
array1d.shape

(4,)

In [32]:
array1d.size

4

In [35]:
array1d.dtype

dtype('int32')

In [36]:
test = np.array([5,4,9],dtype='int64')

In [37]:
test.dtype

dtype('int64')

In [38]:
array1d.strides

(4,)

In [49]:
array1d_str = np.array(['wheat','coffee','bread','eggs','omlette',33])

In [50]:
array1d_str

array(['wheat', 'coffee', 'bread', 'eggs', 'omlette', '33'], dtype='<U11')

In [48]:
array1d_str.dtype

dtype('<U7')

In [45]:
array1d_str

array(['wheat', 'coffee', 'bread', 'eggs'], dtype='<U6')

In [51]:
array1d_str.itemsize

44

In [52]:
array1d_str.dtype

dtype('<U11')

In [53]:
array1d_str.dtype.name

'str352'

In [54]:
array1d_str.itemsize

44

In [55]:
array1d = np.arange(10)

In [56]:
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
array2d

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [78,  1, 23]])

In [58]:
array2d[1,1]

5